// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqzqphklxougnazubslh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxenFwaGtseG91Z25henVic2xoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4ODgyMzksImV4cCI6MjA1NzQ2NDIzOX0.8WxWN9NSkmq4OW71Ck25C4kEZlKrfu_N4xr70lv92uc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);